// 音声ファイルからリップシンク用の振幅データを生成
// 使い方: node generate-lipsync.mjs
// 出力: src/lipsync-data.ts
import { execSync } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FPS = 30;
const SAMPLE_RATE = 44100;
const SAMPLES_PER_FRAME = Math.floor(SAMPLE_RATE / FPS); // 1470サンプル/フレーム

const AUDIO_DIR = path.join(__dirname, "public/audio");
const OUTPUT_FILE = path.join(__dirname, "src/lipsync-data.ts");

function extractAmplitude(audioPath) {
  // ffmpegでPCM（signed 16-bit little-endian, 44100Hz, mono）に変換
  const pcmBuffer = execSync(
    `ffmpeg -i "${audioPath}" -f s16le -acodec pcm_s16le -ar ${SAMPLE_RATE} -ac 1 -loglevel quiet -`,
    { maxBuffer: 100 * 1024 * 1024 }
  );

  const samples = new Int16Array(
    pcmBuffer.buffer,
    pcmBuffer.byteOffset,
    pcmBuffer.byteLength / 2
  );

  // フレームごとのRMS（二乗平均平方根）を計算
  const frames = [];
  for (let i = 0; i < samples.length; i += SAMPLES_PER_FRAME) {
    let sumSq = 0;
    const count = Math.min(SAMPLES_PER_FRAME, samples.length - i);
    for (let j = 0; j < count; j++) {
      const s = samples[i + j] / 32768;
      sumSq += s * s;
    }
    frames.push(Math.sqrt(sumSq / count));
  }

  // 正規化（最大値を1に）
  const max = Math.max(...frames, 0.001);
  let norm = frames.map((v) => v / max);

  // スムージング（前後2フレームの移動平均）
  norm = norm.map((v, i, arr) => {
    const w = [
      arr[i - 2] ?? v,
      arr[i - 1] ?? v,
      v,
      arr[i + 1] ?? v,
      arr[i + 2] ?? v,
    ];
    return w.reduce((a, b) => a + b) / w.length;
  });

  return norm.map((v) => parseFloat(Math.min(v, 1).toFixed(3)));
}

console.log("🎵 リップシンクデータを生成しています...\n");

const result = {};

for (let i = 0; i <= 8; i++) {
  const audioPath = path.join(AUDIO_DIR, `line_${i}.mp3`);
  if (!fs.existsSync(audioPath)) {
    console.log(`⏭️  line_${i}.mp3 なし、スキップ`);
    continue;
  }
  console.log(`📊 line_${i}.mp3 を分析中...`);
  const data = extractAmplitude(audioPath);
  result[i] = data;
  console.log(`   → ${data.length} フレーム分のデータを生成\n`);
}

const tsContent = `// 🤖 Auto-generated by generate-lipsync.mjs — do not edit manually
export const LIPSYNC: Record<number, number[]> = ${JSON.stringify(result, null, 2)};
`;

fs.writeFileSync(OUTPUT_FILE, tsContent);
console.log(`✅ 完了: ${OUTPUT_FILE}`);
